### ISSUE TITLE
Make Twelve of Code Challenges for 1.0.0

### ISSUE THREAD

**Issue by Mesure73L** [twelve-of-code-official/challenges#1]
### Issue Contents

> [!WARNING]
> Spoiler warning, we are talking about the specific challenges in this issue.

- [x] Think of March theme
- [x] Think of March, Challenge 1
- [ ] twelve-of-code-official/website#92
- [x] Think of March, Challenge 2
- [ ] twelve-of-code-official/website#147
- [ ] Think of March, Challenge 3
- [ ] twelve-of-code-official/website#148

~~I will edit this message if we decide we should create the august challenges with the march ones.~~ We do not have enough time to make 6 challenges before March 1.
